# This workflow will install Python dependencies, run tests and lint with a single version of Python
## For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   repository: ChetanVaidya-Minutus/Gitleaks-Minutus
        #   ref: main
        #   token: ${{ secrets.MY_GITHUB_TOKEN }}
        #   path: ./.github/actions/Gitleaks-Minutus

      - name: gitleaks scan
        uses: ChetanVaidya-Minutus/Gitleaks-Minutus@main
        with:
          repository: ChetanVaidya-Minutus/Gitleaks-Minutus
          ref: main
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: ./.github/actions/Gitleaks-Minutus
        # with:
        #   repo_path: "."
        #   config_path: ".gitleaks.toml"
        # env:
        #   GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
