# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  check-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: gitleaks
      #  uses: gitleaks/gitleaks-action@master
        #uses: gitleaks/gitleaks-action@v2
        
      - name: Clone gitleaks/gitleaks-action
        run: |
          git clone https://github.com/gitleaks/gitleaks-action.git
          cd gitleaks-action
          git pull

      - name: Scan for secrets using gitleaks
        uses: ./gitleaks-action
        with:
          repo_path: "."
          config_path: ".gitleaks.toml"
