# This workflow will install Python dependencies, run tests and lint with a single version of Python
## For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.email "chetan.vaidya@minutuscomputing.com"
          git config --global user.name "ChetanVaidya-Minutus"

      - name: Clone gitleaks/gitleaks-action
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          sudo git clone git@github.com:ChetanVaidya-Minutus/Gitleaks-Minutus.git
          cd Gitleaks-Minutus
          git pull

      - name: Scan for secrets using gitleaks
        uses: ./Gitleaks-Minutus
        with:
          repo_path: "."
          config_path: ".gitleaks.toml"

      # - name: gitleaks scan
      #   uses: ChetanVaidya-Minutus/Gitleaks-Minutus@main
      #   with:
      #     repository: ChetanVaidya-Minutus/Gitleaks-Minutus
      #     ref: main
      #     token: ${{ secrets.MY_GITHUB_TOKEN }}
      #     path: ./.github/actions/Gitleaks-Minutus
        # with:
        #   repo_path: "."
        #   config_path: ".gitleaks.toml"
        # env:
        #   GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

#